- hosts: web
  become: yes
  tasks:
  - name: "apt-get update"
    apt:
      update_cache: yes

  - name: "Install nginx"
    apt:
      name: ['nginx']
      state: latest

  - name: "Install git"
    apt:
      name: git
      state: latest
      update_cache: yes       
